### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by stuartcampbell**
BNL would like to have licenses for all BNL produced software.  The preferred license is BSD.

### CODE REVIEW

**Comment by stuartcampbell** [comment]
Bump... is this ok for me to just merge ?

**Comment by yhidaka** [comment]
Hello,

I'm sorry for my late reply. I don't check this email as often as I would
for my BNL email.

As for the license, I'm not familiar with licensing stuff so I have no idea
what I should do. I will follow any of your suggestion.

-Yoshi

**Comment by stuartcampbell** [comment]
No worries, thank you for merging.

**Comment by yhidaka** [comment]
Hi,

 

I didn’t realize the license file was added in a different branch a long time ago. I believe I have just performed the requested merge. I hope this is all I need to do. Please let me know what else, if any, I need to do. I’m sorry again for not understanding what was going on (and maybe still not understanding fully).

 

-Yoshi

**Pull request merged**
